/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define GST_API_VERSION "1.0"

#define GST_LICENSE "LGPL"

#define GST_PACKAGE_NAME "Odo-Viz Gst Plug-in"

#define GST_PACKAGE_ORIGIN "https://github.com"

#define PACKAGE "gst-odo-viz-plugin"

#define PACKAGE_VERSION "1.19.0.1"

